version: '3'
services:
  db:
    image: mysql:5.7@sha256:b3b2703de646600b008cbb2de36b70b21e51e7e93a7fca450d2b08151658b2dd
    ports:
      - "4406:3306"
    restart: always
    environment:
      - MYSQL_DATABASE=elearning_db
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - ./data:/var/lib/mysql:rw
    command: --innodb_use_native_aio=0
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/elearning
    ports:
      - "3002:3000"
    depends_on:
      - db
    environment:
      DB_HOST: db
